name: NodeJS

on:
  push:
    branches: [ "master" ]
    #paths:
    #  '!.github/**'
jobs:
  clone:
    name: clone code
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using private key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          git --version
          pwd
          #first time deploy
          cd /var/www/html/
          sudo git clone https://github.com/MinhSuIt/hello-express
          cd hello-express

          # ! first time
          #cd /var/www/html/hello-express
          #sudo chmod -R 777 ../hello-express
          #sudo git fetch --all
          #sudo git reset --hard origin/master
          ######
          sudo npm install
          #thay bằng pm2 để start ứng dụng có thể thoát cmd mà ko dùng npm run start bình thường
    #khi có bất kì code gì thay đổi:
    #đều pull code về
    #npm install
    #npm run build rồi chạy lại ứng dụng npm run start/pm2 run restart
