name: NodeJS

on:
  push:
    branches: [ "master" ]
    #paths:
    #  '!.github/**'
jobs:
  clone:
    name: clone code
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using private key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          git --version
          pwd
          cd /var/www/html/
          #sudo git clone https://github.com/MinhSuIt/hello-express
          sudo chmod -R 777 hello-express
          cd hello-express
          sudo git fetch --all
          sudo git reset --hard origin/master
          # https://github.com/MinhSuIt/hello-express
          #cd hello-express
          npm install
          #npm run start #thay bằng pm2 để có thể thoát cmd
    #khi có bất kì code gì thay đổi:
    #đều pull code về
    #nếu code thay đổi file package.json thì xóa package.lock và node_modules rồi npm install
    #npm run build rồi chạy lại ứng dụng npm run start/pm2 run restart
